function plot_regions(ylims, i)
global uniq_reg
global nonuniq_reg
global aln_pos
global unreg_ypos
global nonunreg_ypos
global unseq_color
global nonunseq_color
global en_unreg
global en_nonunreg
global fontname
global region_fsize

% Plot unique regions
if en_unreg == true
    for j = 1 : size(uniq_reg{i}, 2)
    	plot([uniq_reg{i}(1, j), uniq_reg{i}(2, j)] + aln_pos(i, 1), ...
            ylims(2) * [unreg_ypos, unreg_ypos], '-', 'LineWidth', 2, ...
            'Color', unseq_color);
    	plot([uniq_reg{i}(1, j), uniq_reg{i}(1, j)] + aln_pos(i, 1), ...
            ylims(2) * (unreg_ypos + [- 0.005, 0.005]), '-', ...
            'LineWidth', 0.1, 'Color', unseq_color);
    	plot([uniq_reg{i}(2, j), uniq_reg{i}(2, j)] + aln_pos(i, 1), ...
            ylims(2) * (unreg_ypos + [- 0.005, 0.005]), '-', ...
            'LineWidth', 0.1, 'Color', unseq_color);
        [v, e] = num2eng(uniq_reg{i}(2, j) - uniq_reg{i}(1, j) + 1, 2);
    	text_label = ['U' num2str(j) ' (' v ' ' e 'bp) \rightarrow'];
    	text(mean(uniq_reg{i}(1 : 2, j)) + aln_pos(i, 1), ...
            ylims(2) * unreg_ypos, text_label, 'Color', unseq_color, ...
            'Rotation', 90, 'HorizontalAlignment', 'right', ...
            'VerticalAlignment', 'middle', 'FontSize', region_fsize, ...
            'FontName', fontname);
    end
end

% Plot non-unique regions
if en_nonunreg == true
    for j = 1 : size(nonuniq_reg{i}, 2)
    	plot([nonuniq_reg{i}(1, j), nonuniq_reg{i}(1, j)] + ...
            aln_pos(i, 1), ...
            ylims(2) * (nonunreg_ypos + [- 0.005, 0.005]), '-', ...
            'LineWidth', 0.1, 'Color', nonunseq_color);
        plot([nonuniq_reg{i}(2, j), nonuniq_reg{i}(2, j)] + ...
            aln_pos(i, 1), ...
            ylims(2) * (nonunreg_ypos + [- 0.005, 0.005]), '-', ...
            'LineWidth', 0.1, 'Color', nonunseq_color);
        plot([nonuniq_reg{i}(1, j), nonuniq_reg{i}(2, j)] + ...
            aln_pos(i, 1), ...
            ylims(2) * [nonunreg_ypos, nonunreg_ypos], '-', ...
            'LineWidth', 2, 'Color', nonunseq_color);
        [v, e] = ...
            num2eng(nonuniq_reg{i}(2, j) - nonuniq_reg{i}(1, j) + 1, 2);
        text_label = ['N' num2str(j) ' (' v ' ' e 'bp) \rightarrow'];
        text(mean(nonuniq_reg{i}(1 : 2, j)) + aln_pos(i, 1), ...
            ylims(2) * nonunreg_ypos, text_label, 'Rotation', 90, ...
            'HorizontalAlignment', 'right', 'Color', nonunseq_color, ...
            'VerticalAlignment', 'middle', 'FontSize', region_fsize, ...
            'FontName', fontname);
    end
end